# Generated by Django 3.1.5 on 2021-01-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210126_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='john_doe@email.com', max_length=254),
        ),
    ]
